### ISSUE TITLE
Does it works for face recognition?

### ISSUE THREAD

**Issue by look4pritam** [omya2003/Facial_Recognition_Final#1]
Does it works?
Under who you did this work?
Face recognition is different and face verification is different. You should have atleast understood it.

Sending single image using network for face recognition will have bandwidth issue for high resolution images.

It will hardly have either 1-2 frames per second which is not at all good for face recognition.

**Comment by omya2003** [comment]
Hello,

I did this work at Bhabha Atomic Research Centre, Mumbai. Yes, it works.
This has both recognition and verification, but focuses more on
verification. Face detection involves locating faces in an image, while
face recognition goes a step further by identifying and matching those
faces to known individuals. Detection is about finding faces(to create
encoding), while recognition is about identifying them based on
pre-existing data.

“Sending single image using network for face recognition will have
bandwidth issue for high resolution images.” You are correct. Which is why
my code resizes image before sending them to server.

“t will hardly have either 1-2 frames per second which is not at all good
for face recognition.”
Not necessarily, as only 1-2 frames are required, where the candidate is
visible clearly.Face recognition is done for all known faces by uploading
known faces as images and encodings are stored at server. This is done
prior to face detection. The person who scans his RFID card, the live image
is checked only against his pre existing encoding. It is considered a match
if known encoding and live encoding are similar to a certain threshold.

**Comment by look4pritam** [comment]
Dear Omi
   Who was your guide at the organization ?If you use RFID then it is face verification only.If you donot use RFID then it will be facerecogntion, but in server-client approach doing recogntion is difficult due to lanecy in the communication. I am also from the same organization, we are already ablt to run face verification and face recogntion on Raspberry Pi without any problem. The server-client approach is not required. Raspberry Pi itself is sufficient in the edge computing mode.So I want to know your guide's name, so that I can convey the same to him or her.
Thanks & regardsPritam Prakash Shete
 On Thursday, December 28, 2023, 01:02:01 AM GMT+5:30, omya2003 ***@***.***> wrote:  
 
 

Hello,

I did this work at Bhabha Atomic Research Centre, Mumbai. Yes, it works.
This has both recognition and verification, but focuses more on
verification. Face detection involves locating faces in an image, while
face recognition goes a step further by identifying and matching those
faces to known individuals. Detection is about finding faces(to create
encoding), while recognition is about identifying them based on
pre-existing data.

“Sending single image using network for face recognition will have
bandwidth issue for high resolution images.” You are correct. Which is why
my code resizes image before sending them to server.

“t will hardly have either 1-2 frames per second which is not at all good
for face recognition.”
Not necessarily, as only 1-2 frames are required, where the candidate is
visible clearly.Face recognition is done for all known faces by uploading
known faces as images and encodings are stored at server. This is done
prior to face detection. The person who scans his RFID card, the live image
is checked only against his pre existing encoding. It is considered a match
if known encoding and live encoding are similar to a certain threshold.

**Comment by look4pritam** [comment]
Who was your guide?

**Comment by look4pritam** [comment]
Abhilash or Pranav or Gurmeet

**Comment by look4pritam** [comment]
We are taking 15-20 images and only 10-15 images are of good quality. We are able to get more than 97% accuracy. It runs live without any latency.

**Comment by look4pritam** [comment]
We 1-2 images the accuracy will be just 80-85% not more than that.

**Comment by omya2003** [comment]
गुरमीत सिंह Gurmeet Singh
वैज्ञानिक अधिकारी Scientific Officer
कंप्यूटर प्रभाग Computer Division
भाभा परमाणु अनुसंधान केंद्र BARC
मुंबई Mumbai - 400 085
